# Generated by Django 5.0.5 on 2024-06-16 14:53

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('birthdate', models.DateField(db_index=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(default='default.jpg', upload_to=account.models.get_timestamp_path, validators=[account.models.validate_file_extension], verbose_name='Фото')),
                ('confirmation_send_date', models.DateField(db_index=True, verbose_name='Дата запроса подтверждения')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user'],
            },
        ),
    ]
