# Generated by Django 5.0.5 on 2024-05-14 10:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=account.models.get_timestamp_path, validators=[account.models.validate_file_extension], verbose_name='Фото'),
        ),
    ]
