version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: 
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL_HOST_USER}
      PGADMIN_DEFAULT_PASSWORD: ${EMAIL_HOST_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  vika:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vika
    env_file: 
      - .env
    depends_on:
      - postgres
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
