# Generated by Django 5.0.5 on 2024-07-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('echoverse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagessettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.customusermodel', verbose_name='Получатель'),
        ),
    ]
