# Generated by Django 5.0.5 on 2024-05-14 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.CreateModel(
            name='IgnoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Игнорируется с')),
                ('ignored_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by', to=settings.AUTH_USER_MODEL, verbose_name='Игнорируемый')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignoring', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игнорируемый пользователь',
                'verbose_name_plural': 'Игнорируемые пользователи',
                'unique_together': {('user', 'ignored_user')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Подписался')),
                ('informator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Информатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user', 'informator')},
            },
        ),
    ]
