# Generated by Django 5.0.5 on 2024-07-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse', '0003_notifications_sender_alter_notifications_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='echoverse.articles', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='savesmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='echoverse.articles', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='viewsmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='echoverse.articles', verbose_name='Статья'),
        ),
    ]
